// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOJsxwTCniPjZaNUNMaQJhvHqI63m16Iw',
    appId: '1:342040001566:web:0775135cac1a8be94d420f',
    messagingSenderId: '342040001566',
    projectId: 'mkart-c7534',
    authDomain: 'mkart-c7534.firebaseapp.com',
    storageBucket: 'mkart-c7534.appspot.com',
    measurementId: 'G-F3803KG23C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS0Vy3_2rTed5lXSESulE9vHhOCLB6eO8',
    appId: '1:342040001566:android:182159b6029bc7ab4d420f',
    messagingSenderId: '342040001566',
    projectId: 'mkart-c7534',
    storageBucket: 'mkart-c7534.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCADtHEDHHeFB-lu3n86a_13oYnDa8EkqY',
    appId: '1:342040001566:ios:f7a49599475a678b4d420f',
    messagingSenderId: '342040001566',
    projectId: 'mkart-c7534',
    storageBucket: 'mkart-c7534.appspot.com',
    iosClientId: '342040001566-ds001ku80t6r57ak81cvodp75e2l6u83.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitirme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCADtHEDHHeFB-lu3n86a_13oYnDa8EkqY',
    appId: '1:342040001566:ios:f7a49599475a678b4d420f',
    messagingSenderId: '342040001566',
    projectId: 'mkart-c7534',
    storageBucket: 'mkart-c7534.appspot.com',
    iosClientId: '342040001566-ds001ku80t6r57ak81cvodp75e2l6u83.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitirme',
  );
}
